// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_index_ from "./routes/[index].tsx";
import * as $index from "./routes/index.tsx";
import * as $old_404 from "./routes/old/_404.tsx";
import * as $old_app from "./routes/old/_app.tsx";
import * as $old_layout from "./routes/old/_layout.tsx";
import * as $old_details from "./routes/old/details.tsx";
import * as $old_faq from "./routes/old/faq.tsx";
import * as $old_index from "./routes/old/index.tsx";
import * as $old_photos from "./routes/old/photos.tsx";
import * as $old_registry from "./routes/old/registry.tsx";
import * as $old_rsvp_group_id_event_id_ from "./routes/old/rsvp/[group_id]/[event_id].tsx";
import * as $old_rsvp_group_id_index from "./routes/old/rsvp/[group_id]/index.tsx";
import * as $old_rsvp_index from "./routes/old/rsvp/index.tsx";
import * as $Hamburger from "./islands/Hamburger.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[index].tsx": $_index_,
    "./routes/index.tsx": $index,
    "./routes/old/_404.tsx": $old_404,
    "./routes/old/_app.tsx": $old_app,
    "./routes/old/_layout.tsx": $old_layout,
    "./routes/old/details.tsx": $old_details,
    "./routes/old/faq.tsx": $old_faq,
    "./routes/old/index.tsx": $old_index,
    "./routes/old/photos.tsx": $old_photos,
    "./routes/old/registry.tsx": $old_registry,
    "./routes/old/rsvp/[group_id]/[event_id].tsx": $old_rsvp_group_id_event_id_,
    "./routes/old/rsvp/[group_id]/index.tsx": $old_rsvp_group_id_index,
    "./routes/old/rsvp/index.tsx": $old_rsvp_index,
  },
  islands: {
    "./islands/Hamburger.tsx": $Hamburger,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
