// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_rsvp_group_name_ from "./routes/api/rsvp-group/[name].ts";
import * as $api_rsvp_name_ from "./routes/api/rsvp/[name].ts";
import * as $api_rsvp_index from "./routes/api/rsvp/index.ts";
import * as $details from "./routes/details.tsx";
import * as $faq from "./routes/faq.tsx";
import * as $index from "./routes/index.tsx";
import * as $photos from "./routes/photos.tsx";
import * as $rsvp from "./routes/rsvp.tsx";
import * as $Hamburger from "./islands/Hamburger.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/rsvp-group/[name].ts": $api_rsvp_group_name_,
    "./routes/api/rsvp/[name].ts": $api_rsvp_name_,
    "./routes/api/rsvp/index.ts": $api_rsvp_index,
    "./routes/details.tsx": $details,
    "./routes/faq.tsx": $faq,
    "./routes/index.tsx": $index,
    "./routes/photos.tsx": $photos,
    "./routes/rsvp.tsx": $rsvp,
  },
  islands: {
    "./islands/Hamburger.tsx": $Hamburger,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
